"""feat_add_analytics_metadata_and_scibert

Revision ID: 7af71ea46719
Revises: 21178132d92e
Create Date: 2026-03-01 14:12:22.034802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7af71ea46719'
down_revision: Union[str, Sequence[str], None] = '21178132d92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('arxiv_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('published_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('documents', sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('documents', sa.Column('embedding_scibert', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_unique_constraint(None, 'documents', ['arxiv_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'embedding_scibert')
    op.drop_column('documents', 'authors')
    op.drop_column('documents', 'categories')
    op.drop_column('documents', 'published_date')
    op.drop_column('documents', 'arxiv_id')
    # ### end Alembic commands ###
